{
 "title": "URL Shortener - System Overview",
 "tags": [
  "url-shortener",
  "distributed"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Request Rate (req/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(urlshortener_requests_total[1m])",
     "legendFormat": "{{instance}} - {{endpoint}}"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(urlshortener_cache_hits_total[5m])) / (sum(rate(urlshortener_cache_hits_total[5m])) + sum(rate(urlshortener_cache_misses_total[5m])))",
     "legendFormat": "Hit Ratio"
    }
   ]
  },
  {
   "title": "Active Hash Ring Nodes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "urlshortener_active_ring_nodes", "legendFormat": "Nodes" }
   ]
  },
  {
   "title": "p95 Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(urlshortener_request_latency_seconds_bucket[1m]))",
     "legendFormat": "p95 {{endpoint}}"
    }
   ]
  },
  {
   "title": "URLs Created Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(urlshortener_urls_created_total)",
     "legendFormat": "Total URLs"
    }
   ]
  },
  {
   "title": "Cache Hits vs Misses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(urlshortener_cache_hits_total[1m])",
     "legendFormat": "Cache HIT"
    },
    {
     "expr": "rate(urlshortener_cache_misses_total[1m])",
     "legendFormat": "Cache MISS"
    }
   ]
  }
 ]
}